### ISSUE TITLE
Plugin fails to load on Rider 2021.2.1

### ISSUE THREAD

**Issue by nathanjwtx** [bodiam/intellij-bootstrap3#71]
Just received a new work laptop and this happens when trying to enable the plugin. Not sure if perhaps I'm missing something else on my laptop? Not encountered this before on other laptops or desktops.

```
Plugin 'nl.jworks.intellij.bootstrap3' failed to initialize and will be disabled. Please restart JetBrains Rider.

java.lang.ClassNotFoundException: com.intellij.plugin.bootstrap.BootstrapPluginApplicationComponent
             PluginClassLoader(plugin=PluginDescriptor(name=Bootstrap 3, id=nl.jworks.intellij.bootstrap3, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\Rider2021.2\plugins\bootstrap3.jar, version=4.1.1, package=null), packagePrefix=null, instanceId=13, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:441)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:380)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:58)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:255)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:77)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
    at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:75)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
    at com.intellij.idea.ApplicationLoader$initApplication$3.execute(ApplicationLoader.kt:107)
    at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1069)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**Comment by bodiam** [comment]
Hi Nathan,

Thanks for reporting. The plugin is quite old and not well maintained anymore, and Jetbrains changed the plugin structure quite a bit which makes this plugin fail.

I have no time at this moment to fix it, but I do take PRs if they address this issue.

Cheers,

Erik

**Comment by erfanbashar** [comment]
is there any way to get rid of this plugin? Deleting the plugin folder and reinstalling the IDE is not working.

**Comment by bodiam** [comment]
I'm sorry, I have no idea. I've never tried this plugin on Rider.

**Comment by codepressed** [comment]
Same happened to me (Intellij version: Community Edition 2022.3.2).

Just go to C:\Users\YourUser\AppData\Roaming\JetBrains\IdeaIC2022.3\plugins and delete the plugin jar
(might be necessary to kill the process from your Task Manager).
